# Generated by Django 3.1 on 2020-08-15 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('titre_wiki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('titre', models.CharField(max_length=100)),
                ('corps', models.CharField(max_length=1000)),
                ('dateCreation', models.TimeField(auto_now=True)),
            ],
        ),
    ]
